# Generated by Django 5.1.12 on 2026-03-29 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwayModeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Whether Away Mode is currently active')),
                ('sunset_window_minutes', models.IntegerField(default=15, help_text='Minutes before/after sunset to randomly turn on lights (total window = 2x this value)')),
                ('off_time_hour', models.IntegerField(default=22, help_text='Hour (24h format) to turn off lights')),
                ('off_time_minute', models.IntegerField(default=30, help_text='Minute to turn off lights')),
                ('off_window_minutes', models.IntegerField(default=15, help_text='Minutes before/after off time to randomly turn off lights')),
                ('last_sunset_on', models.DateField(blank=True, help_text='Last date lights were turned on at sunset', null=True)),
                ('last_night_off', models.DateField(blank=True, help_text='Last date lights were turned off at night', null=True)),
            ],
            options={
                'verbose_name': 'Away Mode Settings',
                'verbose_name_plural': 'Away Mode Settings',
            },
        ),
        migrations.CreateModel(
            name='WemoSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Device name', max_length=255)),
                ('hostname', models.CharField(blank=True, help_text='Device hostname', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Device IP address')),
                ('port', models.IntegerField(blank=True, help_text='Device port', null=True)),
                ('model', models.CharField(blank=True, help_text='Device model', max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, help_text='Device model name', max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Device serial number', max_length=100, null=True, unique=True)),
                ('udn', models.CharField(blank=True, help_text='Unique Device Name', max_length=255, null=True, unique=True)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address', max_length=17, null=True)),
                ('manufacturer', models.CharField(blank=True, help_text='Device manufacturer', max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, help_text='Firmware version', max_length=50, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, help_text='When this device was added to the database')),
                ('disabled', models.BooleanField(default=False, help_text='Whether this device is disabled')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Last time this device was discovered')),
            ],
            options={
                'verbose_name': 'Wemo Switch',
                'verbose_name_plural': 'Wemo Switches',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='SwitchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('switch_on', 'Switch Turned On'), ('switch_off', 'Switch Turned Off'), ('away_mode_on', 'Away Mode Enabled'), ('away_mode_off', 'Away Mode Disabled')], help_text='Type of event', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the event occurred')),
                ('notes', models.TextField(blank=True, help_text="Additional context (e.g., 'Manual', 'Away Mode', 'Scheduled')")),
                ('switch', models.ForeignKey(blank=True, help_text='Related switch (null for away mode events)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wemo.wemoswitch')),
            ],
            options={
                'verbose_name': 'Switch Event',
                'verbose_name_plural': 'Switch Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'event_type'], name='wemo_switch_timesta_7c7baa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SwitchAwaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date this schedule is for')),
                ('planned_on_time', models.DateTimeField(blank=True, help_text='Planned time to turn this switch on (within sunset window)', null=True)),
                ('planned_off_time', models.DateTimeField(blank=True, help_text='Planned time to turn this switch off (within off-time window)', null=True)),
                ('on_executed', models.BooleanField(default=False, help_text='Whether the on action has been executed')),
                ('off_executed', models.BooleanField(default=False, help_text='Whether the off action has been executed')),
                ('switch', models.ForeignKey(help_text='The switch this schedule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='away_schedules', to='wemo.wemoswitch')),
            ],
            options={
                'verbose_name': 'Switch Away Schedule',
                'verbose_name_plural': 'Switch Away Schedules',
                'ordering': ['date', 'planned_on_time'],
                'unique_together': {('switch', 'date')},
            },
        ),
    ]
