# Generated by Django 5.2.16 on 2026-07-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='A single fact about the household.')),
                ('source', models.CharField(choices=[('admin', 'Admin-curated'), ('learned', 'Learned from conversation')], default='admin', max_length=20)),
                ('source_user_id', models.IntegerField(blank=True, null=True)),
                ('source_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(help_text='Personality and voice — how Mycroft speaks.')),
                ('instructions', models.TextField(help_text='Rules and considerations for every response.')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'personalities',
            },
        ),
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField(blank=True, help_text='What Mycroft should know about this user specifically.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
