# Generated by Django 5.2.16 on 2026-07-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab_chatbot', '0003_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
