# Generated by Django 5.2.16 on 2026-07-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab_chatbot', '0004_conversation_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='completion_tokens',
            field=models.IntegerField(blank=True, help_text='Ollama eval_count for this message.', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, help_text='Ollama prompt_eval_count for the request that produced this message.', null=True),
        ),
    ]
