# Generated by Django 5.2.16 on 2026-08-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab_chatbot', '0006_knowledge_message_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdfact',
            name='content',
            field=models.TextField(help_text='One specific, durable fact about the household, written as a standalone sentence. Add a separate row for each fact rather than listing several here. Examples: "The household is based in Raleigh, NC." — "Leo\'s wife is named Dana." — "Trash pickup is Tuesday mornings."'),
        ),
        migrations.AlterField(
            model_name='householdfact',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin-curated'), ('learned', 'Learned from conversation')], default='admin', help_text='Leave as "Admin-curated" for facts you add by hand. "Learned from conversation" is set automatically by auto-learning (Phase 3b) — you won\'t normally choose it yourself.', max_length=20),
        ),
        migrations.AlterField(
            model_name='householdfact',
            name='source_user_id',
            field=models.IntegerField(blank=True, help_text='Auto-learning only: the id of the user who was talking when this fact was extracted. Leave blank for hand-entered facts.', null=True),
        ),
        migrations.AlterField(
            model_name='householdfact',
            name='source_username',
            field=models.CharField(blank=True, help_text='Auto-learning only: the username who was talking when this fact was extracted. Leave blank for hand-entered facts.', max_length=150),
        ),
    ]
