# Generated by Django 5.2.16 on 2026-08-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab_chatbot', '0007_alter_householdfact_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MycroftConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_chat_model', models.CharField(blank=True, help_text='Model new chats start on. Pick from the installed models; leave blank to fall back to the OLLAMA_CHAT_MODEL setting.', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mycroft configuration',
                'verbose_name_plural': 'Mycroft configuration',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='householdfact',
            name='content',
            field=models.TextField(help_text='One specific, durable fact about the household, written as a standalone sentence. Add a separate row for each fact rather than listing several here. Examples: "The household is based in Raleigh, NC." — "Leo\'s wife is named Jennifer." — "Trash pickup is Tuesday mornings."'),
        ),
    ]
